# Churn Modeling for a bank

## Pt 1 Data Preprocessing

In [2]:
#import libraries
import sys
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
print(sys.version)
print(pd.__version__)
print(np.__version__)
print(tf.__version__)

3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
1.2.4
1.20.2
2.4.0


In [4]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [5]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

#### Label Encoding the gender column

In [10]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [14]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

#### One-hot encoding of geography column

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [16]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
X #dummy variables are now moved to the first column of hte matrix

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

#### Split dataset into traning and testing set

In [18]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [28]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(8000, 12) (8000,) (2000, 12) (2000,)


#### Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler

In [29]:
X_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [30]:
X_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 0, 141533.19],
       [0.0, 1.0, 0.0, ..., 1, 1, 11276.48],
       [0.0, 1.0, 0.0, ..., 1, 0, 192950.6]], dtype=object)

In [31]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [33]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

## Building the ANN

#### Initialize the ANN

In [34]:
ann = tf.keras.models.Sequential()

#### Adding the input layer and the first hidden layer

In [35]:
len(X_train[0])

12

In [36]:
ann.add(tf.keras.layers.Dense(units = 12, activation = 'relu'))

#### Adding the second hidden layer

In [37]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

#### Adding the output layer

In [38]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Training the ANN

#### Compile the ANN

In [42]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Training the ANN on the training set

In [43]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6508 - accuracy: 0.6305
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4740 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4454 - accuracy: 0.7963
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4256 - accuracy: 0.8003
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4141 - accuracy: 0.8111
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3822 - accuracy: 0.8270
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3939 - accuracy: 0.8214
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3752 - accuracy: 0.8308
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3755 - accuracy: 0.8270
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3726 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3165 - accuracy: 0.8750
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3302 - accuracy: 0.8652
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3158 - accuracy: 0.8727
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3273 - accuracy: 0.8695
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3267 - accuracy: 0.8667
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3209 - accuracy: 0.8711
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3247 - accuracy: 0.8718
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3257 - accuracy: 0.8644
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3236 - accuracy: 0.8666
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3271 - accuracy: 

## Making the Predictions and Evaluating the Model

In [56]:
#need to scale the customer used for prediction
customer = sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

In [57]:
customer

array([[ 0.98560362, -0.5698444 , -0.57369368, -0.52111599,  0.91601335,
         0.10961719, -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,
         0.9687384 , -0.87203322]])

In [58]:
ann.predict(customer)
#the customer has a 1.6% chance of leaving based on this model

array([[0.01659392]], dtype=float32)

#### Predict the y_test based on X_test values

In [59]:
#X_test is already scaled and in a 2d array
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [62]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

In [65]:
y_pred, y_test

(array([[False],
        [False],
        [False],
        ...,
        [False],
        [False],
        [False]]),
 array([0, 1, 0, ..., 0, 0, 0], dtype=int64))

In [64]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [73]:
#compare y_pred to y_test values
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1500   95]
 [ 195  210]]
              precision    recall  f1-score   support

           0       0.88      0.94      0.91      1595
           1       0.69      0.52      0.59       405

    accuracy                           0.85      2000
   macro avg       0.79      0.73      0.75      2000
weighted avg       0.85      0.85      0.85      2000

0.855
